"""
Django settings for SmartStay project.

Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path

# 🟢 Získání absolutní cesty k hlavní složce projektu
BASE_DIR = Path(__file__).resolve().parent.parent

# 🟢 Základní bezpečnostní nastavení
SECRET_KEY = 'django-insecure-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

DEBUG = True  # 🛑 Nastavit na False v produkci

ALLOWED_HOSTS = []  # 🟢 V produkci přidáš např. ['smartstay.cz']

# 🟢 Instalované aplikace
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 🔵 Naše aplikace
    'checkin',
]

# 🟢 Middleware – zpracovává požadavky a odpovědi
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 🟢 Definice kořenového směrování
ROOT_URLCONF = 'SmartStay.urls'

# 🟢 Nastavení šablon (včetně cesty k vlastní složce šablon)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'checkin' / 'templates'],  # ✅ cesta k šablonám
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 🟢 WSGI aplikace (pro produkční nasazení)
WSGI_APPLICATION = 'SmartStay.wsgi.application'

# 🟢 Nastavení databáze (defaultně SQLite)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 🟢 Validace uživatelů (hesel)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 🟢 Jazyk a časové pásmo
LANGUAGE_CODE = 'cs'  # 🇨🇿 čeština
TIME_ZONE = 'Europe/Prague'

USE_I18N = True
USE_TZ = True

# 🟢 Statické soubory (CSS, JS, obrázky)
STATIC_URL = 'static/'

# 🟢 Výchozí primární klíč pro modely
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ✅ Přesměrování po přihlášení/odhlášení
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
