# Generated by Django 5.2.4 on 2025-08-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0004_remove_guest_id_number_remove_guest_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='Neznámá lokalita', max_length=100),
            preserve_default=False,
        ),
    ]
